<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="3" time="0.150" timestamp="2025-03-09T23:29:29.962751+00:00" hostname="HundredHandSlap"><testcase classname="tests.test_example" name="test_success" time="0.001" /><testcase classname="tests.test_example" name="test_failure" time="0.001"><failure message="assert (1 + 1) == 3">def test_failure():
&gt;       assert 1 + 1 == 3
E       assert (1 + 1) == 3

tests\test_example.py:7: AssertionError</failure></testcase><testcase classname="tests.test_example" name="test_api" time="0.001"><failure message="assert 500 == 200">def test_api():
        response_status = 500  # Simulating API failure
&gt;       assert response_status == 200
E       assert 500 == 200

tests\test_example.py:11: AssertionError</failure></testcase></testsuite></testsuites>